TOP=/home/schueler/downloads/omniORB-4.1.7/build
CURRENT=/home/schueler/CORBA-1/c++
BASE_OMNI_TREE=/home/schueler/downloads/omniORB-4.1.7
VPATH=./
INSTALL=/usr/bin/install -c

include $(TOP)/mk/beforeauto.mk
include /home/schueler/CORBA-1/c++/dir.mk
include $(TOP)/mk/afterauto.mk
